import { useState }                                                           from 'react'
import { useNavigate }                                                         from 'react-router-dom'
import { deleteUser, EmailAuthProvider, reauthenticateWithCredential, sendPasswordResetEmail } from 'firebase/auth'

import { useAuth }   from '@/contexts/AuthContext'
import { useIdioma } from '@/contexts/IdiomaContext'
import { Button }    from '@/components/ui/button'
import { cn }        from '@/lib/utils'
import { PageLayout, Card } from './base'

// ─── Termos e Privacidade ─────────────────────────────────────────────────────

const TERMOS = {
  pt: [
    { titulo: '1. Aceitação dos Termos', texto: 'Ao criar uma conta e utilizar o Lumi, você concorda com estes Termos de Uso.' },
    { titulo: '2. Sobre o Lumi', texto: 'O Lumi é um aplicativo de monitoramento de cuidados capilares que oferece diagnóstico personalizado.' },
    { titulo: '3. Uso da Conta', texto: 'Você é responsável por manter a confidencialidade das suas credenciais de acesso.' },
    { titulo: '4. Dados e Diagnóstico', texto: 'O diagnóstico gerado pelo Lumi é baseado nas respostas fornecidas no questionário.' },
    { titulo: '5. Propriedade Intelectual', texto: 'Todo o conteúdo do Lumi é de propriedade da autora do projeto e está protegido por direitos autorais.' },
    { titulo: '6. Alterações', texto: 'O Lumi pode atualizar estes Termos periodicamente. O uso continuado implica aceitação.' },
  ],
  en: [
    { titulo: '1. Acceptance of Terms', texto: 'By creating an account and using Lumi, you agree to these Terms of Use.' },
    { titulo: '2. About Lumi', texto: 'Lumi is a hair care monitoring application that offers personalized diagnosis.' },
    { titulo: '3. Account Use', texto: 'You are responsible for maintaining the confidentiality of your access credentials.' },
    { titulo: '4. Data and Diagnosis', texto: 'The diagnosis generated by Lumi is based on the answers you provide in the questionnaire.' },
    { titulo: '5. Intellectual Property', texto: 'All Lumi content is the property of the project author and is protected by copyright.' },
    { titulo: '6. Changes', texto: 'Lumi may update these Terms periodically. Continued use implies acceptance.' },
  ],
}

const PRIVACIDADE = {
  pt: [
    { titulo: '1. Dados Coletados', texto: 'O Lumi coleta: nome, e-mail, celular (opcional), respostas do questionário capilar e histórico de diagnósticos.' },
    { titulo: '2. Uso dos Dados', texto: 'Seus dados são utilizados exclusivamente para gerar diagnósticos personalizados. Não vendemos suas informações.' },
    { titulo: '3. Segurança', texto: 'Seus dados são armazenados no Firebase (Google Cloud), com criptografia em trânsito e em repouso.' },
    { titulo: '4. Seus Direitos (LGPD)', texto: 'Em conformidade com a LGPD, você tem direito a acessar, corrigir, exportar e excluir seus dados.' },
    { titulo: '5. Retenção', texto: 'Ao excluir a conta, todos os dados serão removidos em até 30 dias.' },
  ],
  en: [
    { titulo: '1. Data Collected', texto: 'Lumi collects: name, email, phone (optional), hair questionnaire responses and diagnosis history.' },
    { titulo: '2. Data Use', texto: 'Your data is used exclusively to generate personalized diagnoses. We do not sell your information.' },
    { titulo: '3. Security', texto: 'Your data is stored on Firebase (Google Cloud), with encryption in transit and at rest.' },
    { titulo: '4. Your Rights', texto: 'You have the right to access, correct, export and delete your data at any time.' },
    { titulo: '5. Retention', texto: 'When you delete your account, all data will be removed within 30 days.' },
  ],
}

// ─── Modal legal ──────────────────────────────────────────────────────────────

function LegalModal({ titulo, corpo, onClose, fechar }) {
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-6"
      onClick={onClose}
    >
      <div
        className="flex max-h-[82vh] w-full max-w-[480px] flex-col rounded-2xl bg-white"
        onClick={e => e.stopPropagation()}
        style={{ animation: 'lumi-fade-up-soft .22s ease' }}
      >
        <div className="flex items-center justify-between border-b border-lumi-border px-6 py-5">
          <h2 className="font-['Montserrat'] text-base font-semibold text-lumi-black">{titulo}</h2>
          <Button variant="ghost" size="icon-sm" onClick={onClose} aria-label="Fechar">
            <i className="fa-solid fa-xmark text-sm" aria-hidden="true" />
          </Button>
        </div>
        <div className="flex-1 overflow-y-auto px-6 py-5">
          {corpo.map((s, i) => (
            <div key={i} className="mb-5 last:mb-0">
              <p className="mb-1.5 font-['Montserrat'] text-sm font-semibold text-lumi-black">{s.titulo}</p>
              <p className="font-nunito text-sm leading-relaxed text-lumi-gray">{s.texto}</p>
            </div>
          ))}
        </div>
        <div className="border-t border-lumi-border px-6 py-4">
          <Button className="w-full" onClick={onClose}>{fechar}</Button>
        </div>
      </div>
    </div>
  )
}

// ─── ActionRow ────────────────────────────────────────────────────────────────

function ActionRow({ icon, label, desc, onClick, danger = false }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="flex w-full items-center gap-3.5 border-b border-lumi-border py-4 text-left transition hover:opacity-70 last:border-b-0"
    >
      <div className={cn(
        'flex h-10 w-10 shrink-0 items-center justify-center rounded-xl',
        danger ? 'bg-[#FCEBEB]' : 'bg-lumi-input',
      )}>
        <i className={cn('fa-solid text-[15px]', icon, danger ? 'text-[#dc3232]' : 'text-lumi-gray')} aria-hidden="true" />
      </div>
      <div className="flex-1">
        <p className={cn('font-nunito text-sm font-semibold', danger ? 'text-[#dc3232]' : 'text-lumi-black')}>{label}</p>
        {desc && <p className="font-nunito text-xs text-lumi-muted">{desc}</p>}
      </div>
      <i className="fa-solid fa-chevron-right text-[11px] text-lumi-muted" aria-hidden="true" />
    </button>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function PerfilSeguranca() {
  const { user }     = useAuth()
  const { t, idioma } = useIdioma()
  const navigate     = useNavigate()

  const [modal,          setModal]          = useState(null)   // 'termos' | 'privacidade'
  const [confirmarExc,   setConfirmarExc]   = useState(false)
  const [senhaExclusao,  setSenhaExclusao]  = useState('')
  const [erroExclusao,   setErroExclusao]   = useState('')
  const [excluindo,      setExcluindo]      = useState(false)
  const [emailEnviado,   setEmailEnviado]   = useState(false)

  async function trocarSenha() {
    try {
      await sendPasswordResetEmail(user.auth ?? user, user.email)
      setEmailEnviado(true)
      setTimeout(() => setEmailEnviado(false), 5000)
    } catch { alert(t('erro_generico')) }
  }

  async function excluirConta() {
    setErroExclusao(''); setExcluindo(true)
    try {
      const cred = EmailAuthProvider.credential(user.email, senhaExclusao)
      await reauthenticateWithCredential(user, cred)
      await deleteUser(user)
      navigate('/')
    } catch { setErroExclusao(t('ps_senha_errada')) }
    finally { setExcluindo(false) }
  }

  return (
    <>
      <PageLayout titulo={t('ps_titulo')}>

        <Card>
          <p className="mb-1 font-nunito text-[11px] font-semibold uppercase tracking-[.08em] text-lumi-gray">
            {t('ps_acesso')}
          </p>
          <p className="mb-4 font-nunito text-xs leading-relaxed text-lumi-muted">{t('ps_acesso_hint')}</p>

          {emailEnviado && (
            <div className="mb-4 flex items-start gap-2.5 rounded-xl border border-green-200 bg-green-50 px-4 py-3">
              <i className="fa-solid fa-check-circle mt-0.5 text-sm text-green-500" aria-hidden="true" />
              <div>
                <p className="font-nunito text-sm font-semibold text-green-700">{t('ps_email_enviado')}</p>
                <p className="font-nunito text-xs text-green-600 opacity-80">{t('ps_email_enviado_desc')} {user?.email}</p>
              </div>
            </div>
          )}

          <ActionRow icon="fa-key"      label={t('ps_alterar_senha')}  desc={t('ps_alterar_senha_desc')} onClick={trocarSenha} />
          <ActionRow icon="fa-envelope" label={t('ps_email_conta')}    desc={user?.email}                onClick={() => {}} />
        </Card>

        <Card>
          <p className="mb-4 font-nunito text-[11px] font-semibold uppercase tracking-[.08em] text-lumi-gray">
            {t('ps_legal')}
          </p>
          <ActionRow icon="fa-file-lines" label={t('ps_termos')}      desc={t('ps_termos_desc')}      onClick={() => setModal('termos')} />
          <ActionRow icon="fa-shield"     label={t('ps_privacidade')} desc={t('ps_privacidade_desc')} onClick={() => setModal('privacidade')} />
        </Card>

        <Card className="border-red-200">
          <p className="mb-1 font-nunito text-[11px] font-semibold uppercase tracking-[.08em] text-[#dc3232]">
            {t('ps_perigo')}
          </p>
          <p className="mb-4 font-nunito text-xs leading-relaxed text-lumi-muted">{t('ps_perigo_hint')}</p>
          <ActionRow icon="fa-trash" label={t('ps_excluir')} desc={t('ps_excluir_desc')} onClick={() => setConfirmarExc(true)} danger />
        </Card>
      </PageLayout>

      {/* Modal termos / privacidade */}
      {modal === 'termos' && (
        <LegalModal
          titulo={t('termos_titulo')}
          corpo={TERMOS[idioma] ?? TERMOS.pt}
          fechar={t('entendi')}
          onClose={() => setModal(null)}
        />
      )}
      {modal === 'privacidade' && (
        <LegalModal
          titulo={t('privacidade_titulo')}
          corpo={PRIVACIDADE[idioma] ?? PRIVACIDADE.pt}
          fechar={t('entendi')}
          onClose={() => setModal(null)}
        />
      )}

      {/* Modal exclusão */}
      {confirmarExc && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/55 p-6">
          <div className="w-full max-w-[380px] rounded-2xl bg-white p-8">
            <div className="mx-auto mb-4 flex h-[52px] w-[52px] items-center justify-center rounded-full bg-[#FCEBEB]">
              <i className="fa-solid fa-triangle-exclamation text-[22px] text-[#dc3232]" aria-hidden="true" />
            </div>
            <h3 className="mb-2 text-center font-['Montserrat'] text-[17px] font-semibold text-lumi-black">
              {t('ps_excluir_titulo')}
            </h3>
            <p className="mb-5 text-center font-nunito text-sm leading-6 text-lumi-gray">
              {t('ps_excluir_msg')}
            </p>
            <input
              type="password"
              value={senhaExclusao}
              onChange={e => setSenhaExclusao(e.target.value)}
              placeholder={t('ps_excluir_ph')}
              className="mb-2 w-full rounded-[8px] border border-lumi-border bg-lumi-bg px-4 py-3.5 font-nunito text-sm outline-none transition focus:border-lumi-black"
            />
            {erroExclusao && (
              <p className="mb-3 text-center font-nunito text-sm text-[#dc3232]">{erroExclusao}</p>
            )}
            <div className="flex gap-2.5">
              <Button variant="secondary" className="flex-1"
                onClick={() => { setConfirmarExc(false); setSenhaExclusao(''); setErroExclusao('') }}>
                {t('cancelar')}
              </Button>
              <Button
                variant={senhaExclusao ? 'destructive' : 'secondary'}
                className={cn('flex-1', senhaExclusao && 'bg-[#dc3232] text-white hover:bg-[#b52a2a]')}
                onClick={excluirConta}
                disabled={!senhaExclusao || excluindo}
              >
                {excluindo
                  ? <><i className="fa-solid fa-spinner fa-spin text-sm" aria-hidden="true" />{t('ps_excluindo')}</>
                  : t('ps_excluir')}
              </Button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}