import { useEffect, useRef, useState } from 'react'
import { useNavigate }                  from 'react-router-dom'
import { doc, getDoc, updateDoc }       from 'firebase/firestore'
import {
  updateProfile, sendPasswordResetEmail,
  EmailAuthProvider, reauthenticateWithCredential,
  verifyBeforeUpdateEmail, deleteUser,
} from 'firebase/auth'
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage'

import { db, storage } from '@/lib/firebase'
import { useAuth }     from '@/contexts/AuthContext'
import { useIdioma }   from '@/contexts/IdiomaContext'
import { useTheme }    from '@/hooks/useTheme'
import AppShell        from '@/components/lumi/AppShell'
import { Button }      from '@/components/ui/button'
import Input           from '@/components/ui/input'
import PhoneField, { PAISES, formatarCelular } from '@/components/lumi/PhoneField'
import { cn }          from '@/lib/utils'

// só letras (com acentos) e espaço
function somenteLetras(v) {
  return v.replace(/[^\p{L}\s]/gu, '')
}

// termos de uso e política de privacidade

const TERMOS = {
  pt: [
    { titulo: '1. Aceitação dos Termos', texto: 'Ao criar uma conta e utilizar o Lumi, você concorda com estes Termos de Uso.' },
    { titulo: '2. Sobre o Lumi', texto: 'O Lumi é um aplicativo de monitoramento de cuidados capilares que oferece diagnóstico personalizado.' },
    { titulo: '3. Uso da Conta', texto: 'Você é responsável por manter a confidencialidade das suas credenciais de acesso.' },
    { titulo: '4. Dados e Diagnóstico', texto: 'O diagnóstico gerado pelo Lumi é baseado nas respostas fornecidas no questionário.' },
    { titulo: '5. Propriedade Intelectual', texto: 'Todo o conteúdo do Lumi é de propriedade da autora do projeto e está protegido por direitos autorais.' },
    { titulo: '6. Alterações', texto: 'O Lumi pode atualizar estes Termos periodicamente. O uso continuado implica aceitação.' },
  ],
  en: [
    { titulo: '1. Acceptance of Terms', texto: 'By creating an account and using Lumi, you agree to these Terms of Use.' },
    { titulo: '2. About Lumi', texto: 'Lumi is a hair care monitoring application that offers personalized diagnosis.' },
    { titulo: '3. Account Use', texto: 'You are responsible for maintaining the confidentiality of your access credentials.' },
    { titulo: '4. Data and Diagnosis', texto: 'The diagnosis generated by Lumi is based on the answers you provide in the questionnaire.' },
    { titulo: '5. Intellectual Property', texto: 'All Lumi content is the property of the project author and is protected by copyright.' },
    { titulo: '6. Changes', texto: 'Lumi may update these Terms periodically. Continued use implies acceptance.' },
  ],
}

const PRIVACIDADE = {
  pt: [
    { titulo: '1. Dados Coletados', texto: 'O Lumi coleta: nome, e-mail, celular (opcional), respostas do questionário capilar e histórico de diagnósticos.' },
    { titulo: '2. Uso dos Dados', texto: 'Seus dados são utilizados exclusivamente para gerar diagnósticos personalizados. Não vendemos suas informações.' },
    { titulo: '3. Segurança', texto: 'Seus dados são armazenados no Firebase (Google Cloud), com criptografia em trânsito e em repouso.' },
    { titulo: '4. Seus Direitos (LGPD)', texto: 'Em conformidade com a LGPD, você tem direito a acessar, corrigir, exportar e excluir seus dados.' },
    { titulo: '5. Retenção', texto: 'Ao excluir a conta, todos os dados serão removidos em até 30 dias.' },
  ],
  en: [
    { titulo: '1. Data Collected', texto: 'Lumi collects: name, email, phone (optional), hair questionnaire responses and diagnosis history.' },
    { titulo: '2. Data Use', texto: 'Your data is used exclusively to generate personalized diagnoses. We do not sell your information.' },
    { titulo: '3. Security', texto: 'Your data is stored on Firebase (Google Cloud), with encryption in transit and at rest.' },
    { titulo: '4. Your Rights', texto: 'You have the right to access, correct, export and delete your data at any time.' },
    { titulo: '5. Retention', texto: 'When you delete your account, all data will be removed within 30 days.' },
  ],
}

// subcomponentes

function SectionCard({ title, children, action }) {
  return (
    <section className="flex flex-col gap-5 rounded-[16px] bg-surface p-6">
      {(title || action) && (
        <div className="flex items-center justify-between gap-3">
          {title && <h2 className="font-['Montserrat'] text-lg font-semibold text-text">{title}</h2>}
          {action}
        </div>
      )}
      {children}
    </section>
  )
}

function Field({ label, value, onChange, type = 'text', placeholder, hint, disabled }) {
  return (
    <div className="flex flex-col gap-1.5">
      <label className="font-['Nunito_Sans'] text-xs font-semibold text-text-secondary">{label}</label>
      <Input
        type={type}
        value={value}
        onChange={e => onChange?.(e.target.value)}
        placeholder={placeholder}
        disabled={disabled}
        className="py-3 text-sm"
      />
      {hint && <p className="font-['Nunito_Sans'] text-[11px] leading-relaxed text-text-tertiary">{hint}</p>}
    </div>
  )
}

function Segmented({ options, value, onChange }) {
  return (
    <div className="flex items-center rounded-full bg-surface-subtle p-[3px]">
      {options.map(opt => {
        const ativo = value === opt.value
        return (
          <button key={opt.value} type="button" onClick={() => onChange(opt.value)} aria-pressed={ativo}
            className={cn(
              "flex-1 rounded-full py-2 font-['Nunito_Sans'] text-sm font-semibold transition",
              ativo ? 'bg-ink text-white shadow-sm' : 'text-text-tertiary hover:text-text-secondary',
            )}>
            {opt.label}
          </button>
        )
      })}
    </div>
  )
}

function Toggle({ title, desc, value, onChange }) {
  return (
    <div className="flex items-center gap-4">
      <div className="flex flex-1 flex-col gap-1">
        <p className="font-['Montserrat'] text-sm font-semibold text-text">{title}</p>
        {desc && <p className="font-['Nunito_Sans'] text-xs leading-5 text-text-secondary">{desc}</p>}
      </div>
      <button type="button" role="switch" aria-checked={value} onClick={() => onChange(!value)}
        className={cn('relative h-6 w-11 shrink-0 rounded-full transition-colors', value ? 'bg-ink' : 'bg-paper-300')}>
        <span className={cn('absolute top-0.5 h-5 w-5 rounded-full bg-white shadow-sm transition-all', value ? 'left-[22px]' : 'left-0.5')} />
      </button>
    </div>
  )
}

// Linha de ação em lista (Segurança, Conta)
function ActionRow({ icon, label, desc, onClick, last, danger }) {
  return (
    <button type="button" onClick={onClick}
      className={cn('flex w-full items-center gap-3.5 py-3.5 text-left transition hover:opacity-70', !last && 'border-b border-paper-200')}>
      <span className={cn(
        'flex h-10 w-10 shrink-0 items-center justify-center rounded-xl',
        danger ? 'bg-state-negative-soft' : 'bg-surface-subtle',
      )}>
        <i className={cn('fa-solid text-[15px]', icon, danger ? 'text-state-negative' : 'text-text-secondary')} aria-hidden="true" />
      </span>
      <span className="flex-1">
        <span className={cn(`block font-['Nunito_Sans'] text-sm font-semibold`, danger ? 'text-state-negative' : 'text-text')}>{label}</span>
        {desc && <span className="block font-['Nunito_Sans'] text-xs text-text-tertiary">{desc}</span>}
      </span>
      <i className={cn('fa-solid fa-chevron-right text-[11px]', danger ? 'text-state-negative/60' : 'text-text-tertiary')} aria-hidden="true" />
    </button>
  )
}

function LegalModal({ titulo, corpo, fechar, onClose }) {
  return (
    <div className="fixed inset-0 z-[1000] flex items-center justify-center bg-black/50 p-6" onClick={onClose}>
      <div className="flex max-h-[82vh] w-full max-w-[480px] flex-col rounded-2xl bg-surface" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between border-b border-paper-200 px-6 py-5">
          <h2 className="font-['Montserrat'] text-base font-semibold text-text">{titulo}</h2>
          <button type="button" onClick={onClose} aria-label="Fechar"
            className="flex h-8 w-8 items-center justify-center rounded-full text-text-secondary transition hover:bg-surface-subtle">
            <i className="fa-solid fa-xmark text-sm" aria-hidden="true" />
          </button>
        </div>
        <div className="flex-1 overflow-y-auto px-6 py-5">
          {corpo.map((s, i) => (
            <div key={i} className="mb-5 last:mb-0">
              <p className="mb-1.5 font-['Montserrat'] text-sm font-semibold text-text">{s.titulo}</p>
              <p className="font-['Nunito_Sans'] text-sm leading-relaxed text-text-secondary">{s.texto}</p>
            </div>
          ))}
        </div>
        <div className="border-t border-paper-200 px-6 py-4">
          <Button className="w-full" onClick={onClose}>{fechar}</Button>
        </div>
      </div>
    </div>
  )
}

// pagina de perfil, com seções de dados pessoais, notificações, segurança e conta, além de modais para termos e privacidade

export default function PerfilMenu() {
  const { user, logout }            = useAuth()
  const { t, idioma, setIdiomaApp } = useIdioma()
  const { tema, alternar }          = useTheme()
  const navigate                    = useNavigate()
  const fileRef = useRef(null)

  const tr = (key, fb) => { const v = t(key); return (!v || v === key) ? fb : v }

  // dados pessoais
  const [original,  setOriginal]  = useState({})
  const [nome,      setNome]      = useState('')
  const [sobrenome, setSobre]     = useState('')
  const [celular,   setCelular]   = useState('')
  const [ddi,       setDdi]       = useState('+55')
  const [salvandoP, setSalvandoP] = useState(false)
  const [sucessoP,  setSucessoP]  = useState(false)
  const [erroP,     setErroP]     = useState('')

  // foto
  const [fotoURL,   setFotoURL]   = useState(null)
  const [uploading, setUploading] = useState(false)

  // notificações
  const [notif, setNotif]         = useState({ diaria: true, semanal: true, especialista: false })
  const [notifOrig, setNotifOrig] = useState(null)
  const [salvandoN, setSalvandoN] = useState(false)
  const [sucessoN, setSucessoN]   = useState(false)

  // segurança
  const [modal, setModal]               = useState(null)   // 'termos' | 'privacidade'
  const [emailEnviado, setEmailEnviado] = useState(false)

  // alterar e-mail
  const [modalEmail,   setModalEmail]   = useState(false)
  const [novoEmail,    setNovoEmail]    = useState('')
  const [senhaEmail,   setSenhaEmail]   = useState('')
  const [erroEmail,    setErroEmail]    = useState('')
  const [enviandoEmail, setEnviandoEmail] = useState(false)
  const [emailOk,      setEmailOk]      = useState(false)

  // excluir conta
  const [confirmarExc,  setConfirmarExc]  = useState(false)
  const [senhaExclusao, setSenhaExclusao] = useState('')
  const [erroExclusao,  setErroExclusao]  = useState('')
  const [excluindo,     setExcluindo]     = useState(false)

  useEffect(() => {
    if (!user) return
    getDoc(doc(db, 'usuarios', user.uid)).then(snap => {
      if (!snap.exists()) return
      const d = snap.data()
      // celular salvo como "+55 (11) 99999-9999" → separa DDI e número
      const celularSalvo = d.celular ?? ''
      let ddiSalvo = '+55', numSalvo = celularSalvo
      const m = celularSalvo.match(/^(\+\d{1,3})\s*(.*)$/)
      if (m) { ddiSalvo = m[1]; numSalvo = m[2] }
      const dados = { nome: d.nome ?? '', sobrenome: d.sobrenome ?? '', celular: celularSalvo }
      setOriginal(dados)
      setNome(dados.nome); setSobre(dados.sobrenome)
      setDdi(ddiSalvo); setCelular(formatarCelular(numSalvo))
      const n = {
        diaria: d.notificacoes?.diaria ?? true,
        semanal: d.notificacoes?.semanal ?? true,
        especialista: d.notificacoes?.especialista ?? false,
      }
      setNotif(n); setNotifOrig(n)
    })
    setFotoURL(user.photoURL ?? null)
  }, [user])

  const celularCompleto = celular ? `${ddi} ${celular}` : ''
  const modificadoP =
    nome !== original.nome || sobrenome !== original.sobrenome || celularCompleto !== original.celular

  const modificadoN = notifOrig && (
    notif.diaria !== notifOrig.diaria ||
    notif.semanal !== notifOrig.semanal ||
    notif.especialista !== notifOrig.especialista
  )

  async function salvarPessoal() {
    if (!nome.trim() || !sobrenome.trim()) return setErroP(t('obrigatorio'))
    setSalvandoP(true); setErroP('')
    try {
      await updateDoc(doc(db, 'usuarios', user.uid), { nome, sobrenome, celular: celularCompleto })
      await updateProfile(user, { displayName: `${nome} ${sobrenome}` })
      setOriginal({ nome, sobrenome, celular: celularCompleto })
      setSucessoP(true); setTimeout(() => setSucessoP(false), 3000)
    } catch { setErroP(t('erro_generico')) }
    finally { setSalvandoP(false) }
  }

  async function salvarNotif() {
    setSalvandoN(true)
    try {
      await updateDoc(doc(db, 'usuarios', user.uid), { notificacoes: notif })
      setNotifOrig(notif)
      setSucessoN(true); setTimeout(() => setSucessoN(false), 3000)
    } finally { setSalvandoN(false) }
  }

  async function uploadFoto(e) {
    const file = e.target.files[0]
    if (!file) return
    setUploading(true)
    try {
      const storageRef = ref(storage, `usuarios/${user.uid}/foto`)
      await uploadBytes(storageRef, file)
      const url = await getDownloadURL(storageRef)
      await updateProfile(user, { photoURL: url })
      setFotoURL(url)
    } finally { setUploading(false) }
  }

  async function trocarSenha() {
    try {
      await sendPasswordResetEmail(user.auth ?? user, user.email)
      setEmailEnviado(true); setTimeout(() => setEmailEnviado(false), 5000)
    } catch { alert(t('erro_generico')) }
  }

  async function alterarEmail() {
    setErroEmail('')
    if (!novoEmail.trim() || !novoEmail.includes('@')) return setErroEmail(tr('pp_email_invalido', 'Digite um e-mail válido.'))
    if (!senhaEmail) return setErroEmail(tr('pp_email_senha_req', 'Digite sua senha atual.'))
    setEnviandoEmail(true)
    try {
      const cred = EmailAuthProvider.credential(user.email, senhaEmail)
      await reauthenticateWithCredential(user, cred)
      await verifyBeforeUpdateEmail(user, novoEmail.trim())
      setEmailOk(true)
    } catch (err) {
      if (err?.code === 'auth/wrong-password' || err?.code === 'auth/invalid-credential')
        setErroEmail(tr('ps_senha_errada', 'Senha incorreta. Tente novamente.'))
      else if (err?.code === 'auth/email-already-in-use')
        setErroEmail(tr('pp_email_em_uso', 'Este e-mail já está em uso.'))
      else
        setErroEmail(tr('erro_generico', 'Erro ao salvar. Tente novamente.'))
    } finally { setEnviandoEmail(false) }
  }

  function fecharModalEmail() {
    setModalEmail(false); setNovoEmail(''); setSenhaEmail(''); setErroEmail(''); setEmailOk(false)
  }

  async function excluirConta() {
    setErroExclusao(''); setExcluindo(true)
    try {
      const cred = EmailAuthProvider.credential(user.email, senhaExclusao)
      await reauthenticateWithCredential(user, cred)
      await deleteUser(user)
      navigate('/')
    } catch { setErroExclusao(t('ps_senha_errada')) }
    finally { setExcluindo(false) }
  }

  const iniciais = `${nome[0] ?? ''}${sobrenome[0] ?? ''}`.toUpperCase() || 'U'

  return (
    <AppShell>
      <main className="min-h-screen bg-surface-muted px-4 pb-28 pt-5 sm:px-6 lg:px-10 lg:pb-14 lg:pt-8">
        <div className="mx-auto flex max-w-[760px] flex-col gap-6">

          <header className="mb-5 sm:mb-8">
            <h1 className="font-['Montserrat'] text-xl font-semibold leading-[40px] text-text sm:text-2xl">{t('perfil_titulo')}</h1>
            <p className="mt-1 font-['Nunito_Sans'] text-sm leading-5 text-text-secondary">
              {tr('perfil_subtitulo', 'Gerencie seus dados, preferências e segurança da sua conta.')}
            </p>
          </header>

          {/* ── Dados pessoais ── */}
          <SectionCard
            title={t('pp_titulo')}
            action={modificadoP && (
              <Button size="sm" onClick={salvarPessoal} disabled={salvandoP}>
                {salvandoP ? t('salvando') : t('salvar')}
              </Button>
            )}
          >
            {/* foto */}
            <div className="flex flex-wrap items-center gap-5">
              <div className="flex h-[88px] w-[88px] shrink-0 items-center justify-center overflow-hidden rounded-full bg-ink">
                {fotoURL
                  ? <img src={fotoURL} alt="" className="h-full w-full object-cover" />
                  : <span className="font-['Montserrat'] text-2xl font-bold text-white">{iniciais}</span>}
              </div>
              <div className="flex flex-wrap items-center gap-2.5">
                <Button size="sm" onClick={() => fileRef.current?.click()} disabled={uploading}>
                  {uploading ? t('salvando') : tr('pp_trocar_foto', 'Trocar foto')}
                </Button>
                {fotoURL && (
                  <Button size="sm" variant="outline" onClick={() => { setFotoURL(null); updateProfile(user, { photoURL: '' }) }}>
                    {tr('pp_remover_foto', 'Remover foto')}
                  </Button>
                )}
                <input ref={fileRef} type="file" accept="image/*" onChange={uploadFoto} className="hidden" />
              </div>
            </div>

            {sucessoP && (
              <div className="flex items-center gap-2.5 rounded-xl bg-state-positive-soft px-4 py-3">
                <i className="fa-solid fa-circle-check text-sm text-state-positive" aria-hidden="true" />
                <p className="font-['Nunito_Sans'] text-sm font-semibold text-state-positive">{t('salvo')}</p>
              </div>
            )}
            {erroP && (
              <div className="flex items-center gap-2.5 rounded-xl bg-state-negative-soft px-4 py-3">
                <i className="fa-solid fa-circle-exclamation text-sm text-state-negative" aria-hidden="true" />
                <p className="font-['Nunito_Sans'] text-sm text-state-negative">{erroP}</p>
              </div>
            )}

            {/* nome / sobrenome — só letras */}
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label={t('pp_nome')}      value={nome}      onChange={v => setNome(somenteLetras(v))} />
              <Field label={t('pp_sobrenome')} value={sobrenome} onChange={v => setSobre(somenteLetras(v))} />
            </div>

            {/* e-mail como dado da conta + ação */}
            <div className="flex flex-col gap-1.5">
              <label className="font-['Nunito_Sans'] text-xs font-semibold text-text-secondary">{t('pp_email')}</label>
              <div className="flex flex-wrap items-center justify-between gap-3 rounded-[10px] bg-surface-subtle px-4 py-3">
                <span className="font-['Nunito_Sans'] text-sm text-text">{user?.email}</span>
                <button type="button" onClick={() => setModalEmail(true)}
                  className="font-['Nunito_Sans'] text-sm font-semibold text-text underline-offset-2 hover:underline">
                  {tr('pp_alterar_email', 'Alterar e-mail')}
                </button>
              </div>
              <p className="font-['Nunito_Sans'] text-[11px] leading-relaxed text-text-tertiary">
                {tr('pp_email_hint', 'Você pode alterar seu e-mail com confirmação de segurança.')}
              </p>
            </div>

            {/* celular — país + número, só dígitos */}
            <PhoneField
              label={t('pp_celular')}
              ddi={ddi}
              setDdi={setDdi}
              celular={celular}
              setCelular={setCelular}
              placeholder={t('pp_celular_ph')}
            />
          </SectionCard>

          {/* ── Notificações ── */}
          <SectionCard
            title={t('pn_titulo')}
            action={modificadoN && (
              <Button size="sm" onClick={salvarNotif} disabled={salvandoN}>
                {salvandoN ? t('salvando') : t('salvar')}
              </Button>
            )}
          >
            {sucessoN && (
              <div className="flex items-center gap-2.5 rounded-xl bg-state-positive-soft px-4 py-3">
                <i className="fa-solid fa-circle-check text-sm text-state-positive" aria-hidden="true" />
                <p className="font-['Nunito_Sans'] text-sm font-semibold text-state-positive">{t('salvo')}</p>
              </div>
            )}
            <Toggle title={t('pn_diaria')}       desc={t('pn_diaria_desc')}       value={notif.diaria}       onChange={v => setNotif(n => ({ ...n, diaria: v }))} />
            <div className="h-px bg-paper-200" />
            <Toggle title={t('pn_semanal')}      desc={t('pn_semanal_desc')}      value={notif.semanal}      onChange={v => setNotif(n => ({ ...n, semanal: v }))} />
            <div className="h-px bg-paper-200" />
            <Toggle title={t('pn_especialista')} desc={t('pn_especialista_desc')} value={notif.especialista} onChange={v => setNotif(n => ({ ...n, especialista: v }))} />
          </SectionCard>

          {/* ── Preferências ── */}
          <SectionCard title={tr('perfil_preferencias', 'Preferências')}>
            <div className="flex flex-col gap-2.5">
              <p className="font-['Montserrat'] text-sm font-semibold text-text">{t('perfil_idioma')}</p>
              <Segmented value={idioma} onChange={setIdiomaApp}
                options={[{ value: 'pt', label: 'Português' }, { value: 'en', label: 'English' }]} />
            </div>
            <div className="flex flex-col gap-2.5">
              <p className="font-['Montserrat'] text-sm font-semibold text-text">{tr('perfil_aparencia', 'Aparência')}</p>
              <Segmented value={tema} onChange={v => { if (v !== tema) alternar() }}
                options={[
                  { value: 'light', label: tr('perfil_tema_claro', 'Modo claro') },
                  { value: 'dark',  label: tr('perfil_tema_escuro', 'Modo escuro') },
                ]} />
            </div>
          </SectionCard>

          {/* ── Segurança e privacidade ── */}
          <SectionCard title={t('ps_titulo')}>
            {emailEnviado && (
              <div className="flex items-start gap-2.5 rounded-xl bg-state-positive-soft px-4 py-3">
                <i className="fa-solid fa-circle-check mt-0.5 text-sm text-state-positive" aria-hidden="true" />
                <div>
                  <p className="font-['Nunito_Sans'] text-sm font-semibold text-state-positive">{t('ps_email_enviado')}</p>
                  <p className="font-['Nunito_Sans'] text-xs text-state-positive opacity-80">{t('ps_email_enviado_desc')} {user?.email}</p>
                </div>
              </div>
            )}
            <div className="flex flex-col">
              <ActionRow icon="fa-key"        label={t('ps_alterar_senha')} desc={t('ps_alterar_senha_desc')} onClick={trocarSenha} />
              <ActionRow icon="fa-file-lines" label={t('ps_termos')}        desc={t('ps_termos_desc')}        onClick={() => setModal('termos')} />
              <ActionRow icon="fa-shield"     label={t('ps_privacidade')}   desc={t('ps_privacidade_desc')}   onClick={() => setModal('privacidade')} last />
            </div>
          </SectionCard>

          {/* ── Conta ── */}
          <SectionCard title={tr('perfil_conta', 'Conta')}>
            <div className="flex flex-col">
              <ActionRow
                icon="fa-right-from-bracket"
                label={t('perfil_sair')}
                desc={tr('perfil_sair_desc2', 'Encerre sua sessão neste dispositivo.')}
                onClick={logout}
              />
              <ActionRow
                icon="fa-trash-can"
                label={tr('perfil_excluir', 'Excluir minha conta')}
                desc={tr('perfil_excluir_desc', 'Apague sua conta e seus dados do Lumi.')}
                onClick={() => setConfirmarExc(true)}
                danger
                last
              />
            </div>
          </SectionCard>

        </div>
      </main>

      {/* ── Modal alterar e-mail ── */}
      {modalEmail && (
        <div className="fixed inset-0 z-[1000] flex items-end justify-center bg-black/50 p-0 backdrop-blur-sm sm:items-center sm:p-6" onClick={fecharModalEmail}>
          <div className="w-full max-w-[420px] rounded-t-[24px] bg-surface p-6 shadow-[0_-12px_60px_rgba(0,0,0,.18)] sm:rounded-[24px]" onClick={e => e.stopPropagation()}>
            <div className="mx-auto mb-5 h-1 w-10 rounded-full bg-paper-300 sm:hidden" />
            {emailOk ? (
              <div className="flex flex-col items-center gap-3 text-center">
                <div className="grid h-14 w-14 place-items-center rounded-full bg-state-positive-soft">
                  <i className="fa-solid fa-paper-plane text-xl text-state-positive" aria-hidden="true" />
                </div>
                <h2 className="font-['Montserrat'] text-base font-semibold text-text">{tr('pp_email_enviado_titulo', 'Confirme no novo e-mail')}</h2>
                <p className="font-['Nunito_Sans'] text-sm text-text-secondary">
                  {tr('pp_email_enviado_msg', 'Enviamos um link de confirmação para {email}. Após confirmar, seu e-mail de acesso será atualizado.').replace('{email}', novoEmail)}
                </p>
                <Button className="mt-2 w-full" onClick={fecharModalEmail}>{t('entendi')}</Button>
              </div>
            ) : (
              <>
                <div className="mb-5 flex flex-col gap-1">
                  <h2 className="font-['Montserrat'] text-base font-semibold text-text">{tr('pp_alterar_email', 'Alterar e-mail')}</h2>
                  <p className="font-['Nunito_Sans'] text-sm text-text-secondary">{tr('pp_alterar_email_sub', 'Atualize o e-mail usado para acessar sua conta. Pediremos sua senha por segurança.')}</p>
                </div>
                <div className="flex flex-col gap-3">
                  <Field label={tr('pp_novo_email', 'Novo e-mail')} value={novoEmail} onChange={setNovoEmail} type="email" placeholder="novo@email.com" />
                  <Field label={tr('pp_senha_atual', 'Senha atual')} value={senhaEmail} onChange={setSenhaEmail} type="password" placeholder={tr('ps_excluir_ph', 'Digite sua senha')} />
                  {erroEmail && <p className="font-['Nunito_Sans'] text-sm text-state-negative">{erroEmail}</p>}
                </div>
                <div className="mt-5 flex flex-col gap-2">
                  <Button className="w-full" onClick={alterarEmail} disabled={enviandoEmail}>
                    {enviandoEmail ? t('salvando') : tr('pp_enviar_confirmacao', 'Enviar confirmação')}
                  </Button>
                  <Button variant="outline" className="w-full" onClick={fecharModalEmail}>{t('cancelar')}</Button>
                </div>
              </>
            )}
          </div>
        </div>
      )}

      {/* ── Modais legais ── */}
      {modal === 'termos' && (
        <LegalModal titulo={t('termos_titulo')} corpo={TERMOS[idioma] ?? TERMOS.pt} fechar={t('entendi')} onClose={() => setModal(null)} />
      )}
      {modal === 'privacidade' && (
        <LegalModal titulo={t('privacidade_titulo')} corpo={PRIVACIDADE[idioma] ?? PRIVACIDADE.pt} fechar={t('entendi')} onClose={() => setModal(null)} />
      )}

      {/* ── Excluir conta (reautenticação) ── */}
      {confirmarExc && (
        <div className="fixed inset-0 z-[1000] flex items-center justify-center bg-black/55 p-6"
          onClick={() => { setConfirmarExc(false); setSenhaExclusao(''); setErroExclusao('') }}>
          <div className="w-full max-w-[380px] rounded-2xl bg-surface p-8" onClick={e => e.stopPropagation()}>
            <div className="mx-auto mb-4 flex h-[52px] w-[52px] items-center justify-center rounded-full bg-state-negative-soft">
              <i className="fa-solid fa-triangle-exclamation text-[22px] text-state-negative" aria-hidden="true" />
            </div>
            <h3 className="mb-2 text-center font-['Montserrat'] text-[17px] font-semibold text-text">{t('ps_excluir_titulo')}</h3>
            <p className="mb-5 text-center font-['Nunito_Sans'] text-sm leading-6 text-text-secondary">{t('ps_excluir_msg')}</p>
            <input
              type="password" value={senhaExclusao} onChange={e => setSenhaExclusao(e.target.value)}
              placeholder={t('ps_excluir_ph')}
              className="mb-2 w-full rounded-[8px] border border-paper-200 bg-surface-subtle px-4 py-3.5 font-['Nunito_Sans'] text-sm text-text outline-none transition focus:border-ink"
            />
            {erroExclusao && <p className="mb-3 text-center font-['Nunito_Sans'] text-sm text-state-negative">{erroExclusao}</p>}
            <div className="flex flex-col gap-2">
              <button type="button" onClick={excluirConta} disabled={!senhaExclusao || excluindo}
                className="w-full rounded-[10px] bg-state-negative px-4 py-3 font-['Nunito_Sans'] text-sm font-semibold text-white transition hover:opacity-90 disabled:opacity-40">
                {excluindo ? t('ps_excluindo') : tr('ps_excluir_confirmar', 'Sim, excluir minha conta')}
              </button>
              <Button variant="outline" className="w-full"
                onClick={() => { setConfirmarExc(false); setSenhaExclusao(''); setErroExclusao('') }}>
                {t('cancelar')}
              </Button>
            </div>
          </div>
        </div>
      )}
    </AppShell>
  )
}
