import { useRef, useState } from 'react'
import { useNavigate }      from 'react-router-dom'
import { useIdioma }        from '@/contexts/IdiomaContext'
import { Button }           from '@/components/ui/button'
import { cn }               from '@/lib/utils'
import pt from '@/i18n/pt'
import en from '@/i18n/en'

// ─── Conteúdo legal ───────────────────────────────────────────────────────────

const TERMOS = {
  pt: [
    { titulo: '1. Aceitação dos Termos',    texto: 'Ao criar uma conta e utilizar o Lumi, você concorda com estes Termos de Uso. Se não concordar com qualquer parte destes termos, não utilize o aplicativo.' },
    { titulo: '2. Sobre o Lumi',            texto: 'O Lumi é um aplicativo de monitoramento de cuidados capilares que oferece diagnóstico personalizado, recomendações de tratamentos e acompanhamento da rotina capilar.' },
    { titulo: '3. Uso da Conta',            texto: 'Você é responsável por manter a confidencialidade das suas credenciais de acesso. É proibido compartilhar sua conta com terceiros ou utilizá-la para fins ilícitos.' },
    { titulo: '4. Dados e Diagnóstico',     texto: 'O diagnóstico gerado pelo Lumi é baseado nas respostas fornecidas por você no questionário. A precisão das recomendações depende da veracidade das informações fornecidas.' },
    { titulo: '5. Propriedade Intelectual', texto: 'Todo o conteúdo do Lumi — incluindo textos, design, motor de recomendação e interface — é de propriedade da autora do projeto e está protegido por direitos autorais.' },
    { titulo: '6. Alterações nos Termos',   texto: 'O Lumi pode atualizar estes Termos de Uso periodicamente. O uso continuado após as alterações implica na aceitação dos novos termos.' },
  ],
  en: [
    { titulo: '1. Acceptance of Terms',    texto: 'By creating an account and using Lumi, you agree to these Terms of Use. If you do not agree with any part of these terms, please do not use the application.' },
    { titulo: '2. About Lumi',             texto: 'Lumi is a hair care monitoring application that offers personalized diagnosis, treatment recommendations and hair routine tracking.' },
    { titulo: '3. Account Use',            texto: 'You are responsible for maintaining the confidentiality of your access credentials. It is prohibited to share your account with third parties or use it for unlawful purposes.' },
    { titulo: '4. Data and Diagnosis',     texto: 'The diagnosis generated by Lumi is based on the answers you provide in the questionnaire. The accuracy of the recommendations depends on the truthfulness of the information provided.' },
    { titulo: '5. Intellectual Property',  texto: 'All Lumi content — including texts, design, recommendation engine and interface — is the property of the project author and is protected by copyright.' },
    { titulo: '6. Changes to Terms',       texto: 'Lumi may update these Terms of Use periodically. Continued use after changes implies acceptance of the new terms.' },
  ],
}

const PRIVACIDADE = {
  pt: [
    { titulo: '1. Dados Coletados',         texto: 'O Lumi coleta os seguintes dados: nome, e-mail, número de celular (opcional), respostas do questionário capilar, registros de cuidados realizados e histórico de diagnósticos.' },
    { titulo: '2. Como Usamos seus Dados',   texto: 'Seus dados são utilizados exclusivamente para gerar diagnósticos personalizados, criar cronogramas de cuidados e melhorar sua experiência no aplicativo. Não vendemos, alugamos ou compartilhamos suas informações com terceiros para fins comerciais.' },
    { titulo: '3. Armazenamento e Segurança',texto: 'Seus dados são armazenados de forma segura no Firebase (Google Cloud), com criptografia em trânsito e em repouso.' },
    { titulo: '4. Seus Direitos (LGPD)',     texto: 'Em conformidade com a LGPD (Lei nº 13.709/2018), você tem direito a acessar, corrigir, exportar e excluir seus dados a qualquer momento.' },
    { titulo: '5. Cookies e Rastreamento',   texto: 'O Lumi não utiliza cookies de rastreamento para fins publicitários.' },
    { titulo: '6. Retenção de Dados',        texto: 'Seus dados são mantidos enquanto sua conta estiver ativa. Ao excluir sua conta, todos os dados pessoais serão removidos permanentemente dos nossos servidores em até 30 dias.' },
    { titulo: '7. Contato',                  texto: 'Em caso de dúvidas sobre esta Política de Privacidade, entre em contato através do e-mail de suporte disponível no aplicativo.' },
  ],
  en: [
    { titulo: '1. Data Collected',    texto: 'Lumi collects the following data: name, email, phone number (optional), hair questionnaire responses, care records and diagnosis history.' },
    { titulo: '2. How We Use Your Data', texto: 'Your data is used exclusively to generate personalized diagnoses, create care schedules and improve your experience in the application. We do not sell, rent or share your information with third parties for commercial purposes.' },
    { titulo: '3. Storage and Security', texto: 'Your data is stored securely on Firebase (Google Cloud), with encryption in transit and at rest.' },
    { titulo: '4. Your Rights',       texto: 'You have the right to access, correct, export and delete your data at any time.' },
    { titulo: '5. Cookies and Tracking', texto: 'Lumi does not use tracking cookies for advertising purposes.' },
    { titulo: '6. Data Retention',    texto: 'Your data is kept while your account is active. When you delete your account, all personal data will be permanently removed from our servers within 30 days.' },
    { titulo: '7. Contact',           texto: 'If you have questions about this Privacy Policy, please contact us through the support email available in the application.' },
  ],
}

const TEXTOS = { pt, en }

// ─── Drawer/Modal legal ───────────────────────────────────────────────────────

function LegalSheet({ conteudo, fechar, onClose, isMobile }) {
  const startY   = useRef(null)
  const currentY = useRef(null)
  const sheetRef = useRef(null)

  function onTouchStart(e) { startY.current = e.touches[0].clientY }
  function onTouchMove(e) {
    const delta = e.touches[0].clientY - startY.current
    currentY.current = delta
    if (delta > 0 && sheetRef.current) {
      sheetRef.current.style.transform = `translateY(${delta}px)`
      sheetRef.current.style.transition = 'none'
    }
  }
  function onTouchEnd() {
    if (currentY.current > 120) { onClose() }
    else if (sheetRef.current) {
      sheetRef.current.style.transform = 'translateY(0)'
      sheetRef.current.style.transition = 'transform .3s ease'
    }
    currentY.current = null
  }

  return (
    <div
      className="fixed inset-0 z-[100] flex bg-black/60"
      style={{ alignItems: isMobile ? 'flex-end' : 'center', justifyContent: isMobile ? 'stretch' : 'center', padding: isMobile ? 0 : '40px' }}
      onClick={onClose}
    >
      <div
        ref={sheetRef}
        onClick={e => e.stopPropagation()}
        className={cn(
          'force-light flex max-h-[88vh] w-full flex-col bg-white',
          isMobile ? 'rounded-t-[24px]' : 'max-w-[520px] rounded-[24px]',
        )}
        style={{ animation: isMobile ? 'drawerUp .32s cubic-bezier(.32,0,.67,0) forwards' : 'lumi-fade-up-soft .25s ease forwards' }}
      >
        {/* Alça drag — só mobile */}
        {isMobile && (
          <div
            className="flex cursor-grab justify-center pb-3 pt-4"
            onTouchStart={onTouchStart}
            onTouchMove={onTouchMove}
            onTouchEnd={onTouchEnd}
            aria-hidden="true"
          >
            <div className="h-1 w-9 rounded-full bg-lumi-border" />
          </div>
        )}

        {/* Header */}
        <div className={cn(
          'flex items-center justify-between border-b border-[#F0F0F0]',
          isMobile ? 'px-6 pb-4' : 'px-7 py-5',
        )}>
          <h2 className="font-heading text-[17px] font-semibold text-lumi-black">{conteudo.titulo}</h2>
          {!isMobile && (
            <Button variant="ghost" size="icon-sm" onClick={onClose} aria-label="Fechar">
              <i className="fa-solid fa-xmark text-sm" aria-hidden="true" />
            </Button>
          )}
        </div>

        {/* Corpo */}
        <div className={cn('flex-1 overflow-y-auto', isMobile ? 'px-6 py-5' : 'px-7 py-6')}>
          {conteudo.corpo.map((s, i) => (
            <div key={i} className="mb-6 last:mb-0">
              <p className="mb-1.5 font-heading text-sm font-semibold text-lumi-black">{s.titulo}</p>
              <p className="font-nunito text-sm leading-relaxed text-lumi-gray">{s.texto}</p>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className={cn('border-t border-[#F0F0F0]', isMobile ? 'px-6 pb-10 pt-4' : 'px-7 pb-7 pt-5')}>
          <Button size="lg" className="w-full" onClick={onClose}>{fechar}</Button>
        </div>
      </div>
    </div>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function Splash() {
  const { idioma, setIdiomaApp } = useIdioma()
  const navigate                 = useNavigate()
  const [langOpen, setLangOpen]  = useState(false)
  const [modal, setModal]        = useState(null)
  const isMobile = typeof window !== 'undefined' && window.innerWidth < 1024

  const t = (chave) => TEXTOS[idioma]?.[chave] ?? TEXTOS.pt[chave] ?? chave

  const conteudoModal = modal === 'termos'
    ? { titulo: t('termos_titulo'),      corpo: TERMOS[idioma]       ?? TERMOS.pt,      fechar: t('entendi') }
    : modal === 'privacidade'
    ? { titulo: t('privacidade_titulo'), corpo: PRIVACIDADE[idioma]  ?? PRIVACIDADE.pt, fechar: t('entendi') }
    : null

  return (
    <div className="splash-root relative flex min-h-screen w-full flex-col overflow-hidden">
      <style>{`
        @keyframes scaleIn { from{transform:scale(1.06)} to{transform:scale(1)} }
        @keyframes drawerUp { from{transform:translateY(100%)} to{transform:translateY(0)} }
        .splash-bg   { animation: scaleIn 2s ease forwards }
        .splash-fi   { animation: lumi-fade-up-soft .8s .1s ease both }
        .splash-fu0  { animation: lumi-fade-up-soft .7s .3s ease both }
        .splash-fu1  { animation: lumi-fade-up-soft .7s .5s ease both }
        .splash-fu2  { animation: lumi-fade-up-soft .7s .7s ease both }
      `}</style>

      {/* Fundo */}
      <div className="splash-bg absolute inset-0">
        <img src="/hero.jpg" alt="" aria-hidden="true"
          className="h-full w-full object-cover object-[center_30%]" />
      </div>
      <div className="absolute inset-0 bg-gradient-to-b from-black/20 via-black/0 via-[62%] to-black/90" />

      <div className="relative z-10 flex flex-1 flex-col">

        {/* Top bar */}
        <div className="splash-fi flex items-center justify-between px-6 pt-10 lg:px-[68px] lg:pt-12">
          <h1 className="font-serif text-[32px] italic font-normal leading-none text-white lg:text-[64px]">
            Lumi
          </h1>

          {/* Seletor de idioma */}
          <div className="relative">
            <button
              type="button"
              onClick={() => setLangOpen(o => !o)}
              className="flex items-center gap-2 font-nunito text-base font-semibold text-white/70 transition hover:text-white/95"
              aria-expanded={langOpen}
              aria-label="Selecionar idioma"
            >
              {t('splash_lang')}
              <i className={cn('fa-solid text-base', langOpen ? 'fa-chevron-up' : 'fa-chevron-down')} aria-hidden="true" />
            </button>

            {langOpen && (
              <div className="absolute right-0 top-[calc(100%+8px)] z-[99] min-w-[130px] overflow-hidden rounded-[14px] border border-white/10 bg-[rgba(20,20,18,0.97)]">
                {['pt', 'en'].map(key => (
                  <button
                    key={key}
                    type="button"
                    onClick={() => { setIdiomaApp(key); setLangOpen(false) }}
                    className={cn(
                      'block w-full px-4 py-2.5 text-left font-nunito text-sm transition hover:bg-white/[.06] hover:text-white',
                      idioma === key ? 'font-bold text-white' : 'font-normal text-white/65',
                    )}
                  >
                    {TEXTOS[key].splash_lang}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="flex-1" />

        {/* Rodapé */}
        <div className="splash-fu0 px-6 pb-[45px] lg:px-[68px]">
          <h2 className="splash-fu0 mb-6 font-heading text-[32px] font-medium leading-[1.2] text-white lg:max-w-[560px] lg:text-[48px]">
            {t('splash_headline')}
          </h2>

          <div className="splash-fu1 flex flex-col gap-4 lg:flex-row">
            <Button
              size="lg"
              className="w-full bg-white text-[#1E1E1F] hover:bg-white/90 lg:w-auto lg:min-w-[200px]"
              onClick={() => navigate('/cadastro')}
            >
              {t('splash_criar')}
            </Button>
            <Button
              size="lg"
              variant="outline"
              className="w-full border-white/20 bg-white/30 text-white hover:bg-white/40 lg:w-auto lg:min-w-[200px]"
              onClick={() => navigate('/login')}
            >
              {t('splash_entrar')}
            </Button>
          </div>

          <p className="splash-fu2 mt-8 text-center font-nunito text-sm leading-[1.7] text-white/40 lg:text-left">
            {t('splash_termos_pre')}{' '}
            <button
              type="button"
              className="text-white/55 underline transition hover:text-white/90"
              onClick={() => setModal('termos')}
            >
              {t('splash_termos_link1')}
            </button>
            {' '}{t('splash_termos_e')}{' '}
            <button
              type="button"
              className="text-white/55 underline transition hover:text-white/90"
              onClick={() => setModal('privacidade')}
            >
              {t('splash_termos_link2')}
            </button>.
          </p>
        </div>
      </div>

      {conteudoModal && (
        <LegalSheet
          conteudo={conteudoModal}
          fechar={conteudoModal.fechar}
          onClose={() => setModal(null)}
          isMobile={isMobile}
        />
      )}
    </div>
  )
}